name: prueba
description: "A new Flutter project."

publish_to: "none" # No publicar en pub.dev, esto es para proyectos privados

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  connectivity_plus: ^6.1.2

  cupertino_icons: ^1.0.8
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/portada.png
    - assets/images/fondo.png

  # Si estás usando imágenes o cualquier otro recurso, añádelo aquí
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Si usas fuentes personalizadas, añádelas también aquí.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
