name: ejercicio_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/obey1.jpg
    - assets/images/obey2.jpg
    - assets/images/obey3.jpg
    - assets/images/obey4.jpg
    - assets/images/obey5.jpg
    - assets/images/obey6.jpg
    - assets/images/gato1.jpg
    - assets/images/01.jpg
    - assets/images/02.jpg
    - assets/images/03.jpg
    - assets/images/04.jpg
    - assets/images/05.jpg
    - assets/images/06.jpg
    - assets/images/07.jpeg
    - assets/images/08.jpg
    - assets/images/09.jpeg
    - assets/images/10.jpg
    - assets/images/11.jpg
    - assets/images/12.jpg
    - assets/images/add.png
    